### ISSUE TITLE
AttributeError: 'ServerInterface' object has no attribute 'add_help_message'

### ISSUE THREAD

**Issue by Huxzhi** [TISUnion/daycount#1]
MCDR的版本1.3
是这个 `add_help_message()` 方法没了么
新版要怎么写啊

```py
[MCDR] [14:02:16] [TaskExecutor/WARNING]: Plugin ID of RegularPlugin[file=daycount.py,path=plugins\daycount.py,state=0] not found, use fallback id daycount instead
[MCDR] [14:02:16] [TaskExecutor/WARNING]: RegularPlugin[file=daycount.py,path=plugins\daycount.py,state=0] doesn't specific a version, use fallback version 0.0.0

Traceback (most recent call last):
  File "G:\MCDReforged\mcdreforged\plugin\plugin_manager.py", line 447, in trigger_listener
    listener.execute(self.mcdr_server.server_interface, *args)
  File "G:\MCDReforged\mcdreforged\plugin\plugin_event.py", line 79, in execute
    return self.callback(*args, **kwargs)
  File "plugins\daycount.py", line 23, in on_load
    server.add_help_message('!!day', '显示今天是开服第几天')
AttributeError: 'ServerInterface' object has no attribute 'add_help_message'
```

```py
[MCDR] [14:02:16] [MainThread/INFO]: 语言已设置为 zh_cn
[MCDR] [14:02:16] [MainThread/INFO]: 编码 / 解码方式已设置为 utf-8 / cp936
[MCDR] [14:02:16] [MainThread/INFO]: 插件文件夹列表:
[MCDR] [14:02:16] [MainThread/INFO]: - plugins
[MCDR] [14:02:16] [MainThread/INFO]: 解析处理器已设置为 vanilla_handler
[MCDR] [14:02:16] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [14:02:16] [TaskExecutor/WARNING]: Plugin ID of RegularPlugin[file=daycount.py,path=plugins\daycount.py,state=0] not found, use fallback id daycount instead
[MCDR] [14:02:16] [TaskExecutor/WARNING]: RegularPlugin[file=daycount.py,path=plugins\daycount.py,state=0] doesn't specific a version, use fallback version 0.0.0
[MCDR] [14:02:16] [TaskExecutor/INFO]: 插件 daycount@0.0.0 已加载
[MCDR] [14:02:16] [TaskExecutor/INFO]: 插件 join_motd@1.0.0 已加载
[MCDR] [14:02:16] [TaskExecutor/INFO]: 插件 quick_backup_multi@1.1.0 已加载
[MCDR] [14:02:16] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=daycount@0.0.0,priority=1000,callback=<function on_load at 0x0000023DC89881F0>]
Traceback (most recent call last):
  File "G:\MCDReforged\mcdreforged\plugin\plugin_manager.py", line 447, in trigger_listener
    listener.execute(self.mcdr_server.server_interface, *args)
  File "G:\MCDReforged\mcdreforged\plugin\plugin_event.py", line 79, in execute
    return self.callback(*args, **kwargs)
  File "plugins\daycount.py", line 23, in on_load
    server.add_help_message('!!day', '显示今天是开服第几天')
AttributeError: 'ServerInterface' object has no attribute 'add_help_message'
[MCDR] [14:02:16] [TaskExecutor/INFO] [quick_backup_multi]: Config file loaded
[MCDR] [14:02:16] [TaskExecutor/INFO]: 共加载: 3 个插件; 已加载插件数: 4
```

**Comment by Tenktau** [comment]
AttributeError: 'ServerInterface' object has no attribute 'add_help_message'
-----------------------------------------------------------------------------------
请将**add**_help_message()更改为**register**_help_message()
